name: Apply infra and deploy

on:
 push:
  branches:
   - main

jobs:
 apply:
  runs-on: ubuntu-latest

  env:
   ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
   ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
   ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
   ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

  
  steps:
   - name: 'Checkout'
     uses: actions/checkout@v3
        
   - name: 'Azure Login'
     uses: azure/login@v1
     with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

   - name: Get AKS config
     id: set-context
     uses: azure/aks-set-context@v3
     with:
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

   - name: Setup kubectl
     id: install-kubectl
     uses: azure/setup-kubectl@v3

   - name: 'Setup Terraform'
     uses: hashicorp/setup-terraform@v2

   - name: 'Terraform init + plan'
     working-directory: terraform/aks
     run: |
      terraform init
      terraform plan
        
   - name: 'Terraform apply'
     working-directory: terraform/aks
     run: |
      terraform apply -auto-approve

   - name: 'Install Helmfile + plugins'
     run: |
       sudo snap install helm --classic
       curl -L https://github.com/roboll/helmfile/releases/latest/download/helmfile_linux_amd64 -o /usr/local/bin/helmfile
       chmod +x /usr/local/bin/helmfile
       helm plugin install https://github.com/databus23/helm-diff
       helm plugin install https://github.com/jkroepke/helm-secrets

   - name: Debug Helmfile template output
     working-directory: helmfiles
     run: helmfile -e dev template

   - name: 'Deploy Dev environment with Helmfile'
     working-directory: helmfiles
     run: helmfile -e dev apply

   - name: 'Deploy Stage environment with Helmfile'
     working-directory: helmfiles
     run: helmfile -e stage apply
