name: Apply infra and deploy

on: workflow_dispatch

jobs:
 apply:
  runs-on: ubuntu-latest

  steps:
   - name: 'Checkout'
     uses: actions/checkout@v3
        
   - name: 'Azure Login'
     uses: azure/login@v1
     with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

   - name: 'Setup Terraform'
     uses: hashicorp/setup-terraform@v2

   - name: 'Terraform Destroy'
     working-directory: terraform/aks
     run: |
      terraform init
      terraform destroy -auto-approve